
import "./_styles/globals.css"

export const metadata = {
  title: 'DocuChat',
  // description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body>

        
     
    
        {children}
      
        
        </body>
     
      
    </html>
  )
}
